name: "Seplos 19200 Addon"
description: "Read Seplos V2/V16 BMS data via RS485 and publish it to HA via MQTT"
version: "1.0.0-beta4"
slug: "seplos_mqtt_rs485_add-on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
watchdog: "http://[HOST]:8080/health"
uart: true
usb: true
hassio_api: true
homeassistant_api: false
services:
  - mqtt:need
panel_icon: "mdi:battery"
options:
  rs485_remote_ip: ""
  rs485_remote_port: 4196
  serial_interface: "/dev/ttyUSB1"
  number_of_packs: 4
  min_cell_voltage: 2.5
  max_cell_voltage: 3.65
  mqtt_topic: "seplos"
  update_mode:
    name: Update Mode
    description: "fixed = use single interval | dynamic = switch between active/idle based on battery power"
    required: false
    type: list
    default: "fixed"
    options:
      - "fixed"
      - "dynamic"

  mqtt_update_interval:   # used when mode = fixed
    name: Fixed Update Interval (seconds)
    description: Polling interval when update_mode = fixed
    required: false
    type: integer
    default: 10
    min: 5
    max: 900

  active_interval:        # used when mode = dynamic
    name: Active Interval (seconds)
    description: Fast polling when battery is charging or discharging
    required: false
    type: integer
    default: 10
    min: 5
    max: 300

  idle_interval:          # used when mode = dynamic
    name: Idle Interval (seconds)
    description: Slow polling when battery is idle
    required: false
    type: integer
    default: 300
    min: 30
    max: 900

  active_power_threshold: # Watts absolute value
    name: Active Power Threshold (W)
    description: If |dis_charge_power| > this value → considered active
    required: false
    type: integer
    default: 50
    min: 10
    max: 500
  enable_ha_discovery: false
  ha_discovery_prefix: "homeassistant"
  invert_ha_dis_charge_measurements: false
  logging_level: "info"
schema:
  rs485_remote_ip: "str?"
  rs485_remote_port: "int?"
  serial_interface: "str"
  number_of_packs: "int(1,16)"
  min_cell_voltage: "float"
  max_cell_voltage: "float"
  mqtt_topic: "str"
  mqtt_update_interval: "int"
  enable_ha_discovery: "bool"
  ha_discovery_prefix: "str"
  invert_ha_dis_charge_measurements: "bool"
  logging_level: "list(info|error|debug)"
